#!/bin/bash
# regen-wayland.sh — maintainer-only.
#
# Runs wayland-scanner against the protocol XMLs vendored in protocols/
# and produces two outputs:
#
#   wayluigi_wayland.c          (committed; users compile this)
#       Concatenated private-code: interface tables and message
#       signatures backing the extern declarations in luigi.h's
#       #ifdef UI_WAYLAND block.
#
#   protocols/_generated_headers.h   (committed)
#       Concatenated client-header: enums, opaque struct forward
#       declarations, inline accessor functions (e.g.
#       xdg_toplevel_set_title). Spliced into luigi.h between
#       /* @WAYLAND_PROTOCOL_HEADERS_BEGIN@ */ and the matching END
#       marker. The splice happens automatically if those markers
#       exist; otherwise we just leave the file for inspection.
#
# Dependencies (maintainer only — users never run this):
#   wayland-scanner (xbps: wayland-devel)

set -euo pipefail

cd "$(dirname "$0")"

PROTOCOLS=(
    xdg-shell
    xdg-decoration-unstable-v1
    fractional-scale-v1
    viewporter
    # cursor-shape-v1: deferred. Its get_tablet_tool_v2 request makes
    # the generated bindings depend on zwp_tablet_tool_v2_interface
    # from the tablet protocol. MVP uses the wl_cursor theme fallback
    # (PLAN.md step 4) instead. Re-add cursor-shape-v1 alongside
    # tablet-unstable-v2 when we want nicer cursors.
)

OUT_C=wayluigi_wayland.c
OUT_H=protocols/_generated_headers.h

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# Generate each protocol's output into its own file first.
# (`wayland-scanner ... /dev/stdout` doesn't compose with redirection
# inside a brace group — each invocation truncates the redirect
# target, leaving only the last protocol's output and corrupting it.)
for p in "${PROTOCOLS[@]}"; do
    wayland-scanner private-code  "protocols/$p.xml" "$TMP/$p.c"
    wayland-scanner client-header "protocols/$p.xml" "$TMP/$p.h"
done

# --- private-code → wayluigi_wayland.c -----------------------------
{
    cat <<'EOF'
/* wayluigi_wayland.c — generated by regen-wayland.sh, do not edit.
 *
 * Concatenated `wayland-scanner private-code` output for each
 * protocol vendored in protocols/. Contains the interface tables
 * and message signatures referenced by the inline accessor
 * functions in luigi.h's #ifdef UI_WAYLAND block.
 *
 * Build: gcc luigi_example.c wayluigi_wayland.c -DUI_WAYLAND \
 *            -lwayland-client -lxkbcommon -lrt -lm -o luigi
 */

EOF
    for p in "${PROTOCOLS[@]}"; do
        echo "/* ============ $p ============ */"
        cat "$TMP/$p.c"
        echo
    done
} > "$OUT_C"

echo "wrote $OUT_C ($(wc -l < "$OUT_C") lines)"

# --- client-header → protocols/_generated_headers.h ----------------
{
    cat <<'EOF'
/* _generated_headers.h — generated by regen-wayland.sh.
 *
 * Concatenated `wayland-scanner client-header` output for each
 * vendored protocol. The contents of this file are spliced into
 * luigi.h's #ifdef UI_WAYLAND block by regen-wayland.sh so the
 * Wayland backend implementation can call the inline accessor
 * functions (xdg_toplevel_set_title, etc.) directly.
 *
 * Kept in protocols/ for inspection and diffing across protocol
 * version bumps.
 */

EOF
    for p in "${PROTOCOLS[@]}"; do
        echo "/* ============ $p ============ */"
        cat "$TMP/$p.h"
        echo
    done
} > "$OUT_H"

echo "wrote $OUT_H ($(wc -l < "$OUT_H") lines)"

# --- splice $OUT_H into luigi.h between markers --------------------
if grep -q '@WAYLAND_PROTOCOL_HEADERS_BEGIN@' luigi.h 2>/dev/null; then
    awk -v hf="$OUT_H" '
        /@WAYLAND_PROTOCOL_HEADERS_BEGIN@/ {
            print
            while ((getline line < hf) > 0) print line
            close(hf)
            inside = 1
            next
        }
        /@WAYLAND_PROTOCOL_HEADERS_END@/ {
            inside = 0
        }
        !inside { print }
    ' luigi.h > luigi.h.tmp && mv luigi.h.tmp luigi.h
    echo "spliced $OUT_H into luigi.h between WAYLAND_PROTOCOL_HEADERS markers"
else
    echo "note: luigi.h has no WAYLAND_PROTOCOL_HEADERS markers yet — splice skipped"
fi
